#!/bin/bash

if [ -e "/Library/OpenSC/etc/opensc.conf" ]
then
	mv /Library/OpenSC/etc/opensc.conf /Library/OpenSC/etc/opensc.conf.orig
fi
mkdir -p /Library/OpenSC/etc
ln -sf /Library/nPA/etc/opensc.conf /Library/OpenSC/etc

for f in /Library/nPA/bin/*
do
	ln -sf $f /usr/local/bin
done
