import "wudfddi.idl";

[
    uuid(8B9C88E9-7E63-46c7-832B-D48D0290E4BF),
    version(1.0),
    helpstring("VirtualSCReader Driver Type Library")
]
library VirtualSCReaderDriverLib
{
    importlib("stdole2.tlb");
    [
        uuid(d4112073-d09b-458f-a5aa-35ef21eef5de),		   
        //uuid(10654262-B9BD-4636-8890-F66362CCC207),
        helpstring("VirtualSCReader Class")
    ]
    coclass VirtualSCReaderDriver
    {
        [default] interface IDriverEntry;
    };
};
