name: Build

on:
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - '**.in'
      - '**.sh'
      - '**.py'
      - '**.java'
      - .github/workflows/ci.yml
  push:

permissions:
  contents: read

jobs:
  virtualsmartcard-macos:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v6
    - run: .github/build-virtualsmartcard.sh macos
    - uses: actions/upload-artifact@v4
      with:
        name: virtualsmartcard-macos
        path:
          virtualsmartcard/virtualsmartcard*.dmg

  virtualsmartcard-ubuntu:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - run: .github/build-virtualsmartcard.sh ubuntu
    - uses: actions/upload-artifact@v4
      with:
        name: virtualsmartcard
        path:
          virtualsmartcard/virtualsmartcard*.tar.gz

  ccid-ubuntu:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - run: .github/build-ccid.sh ubuntu
    - uses: actions/upload-artifact@v4
      with:
        name: ccid-emulator
        path:
          ccid/ccid-emulator*.tar.gz

  pcsc-relay-macos:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v6
    - run: .github/build-pcsc-relay.sh macos

  pcsc-relay-ubuntu:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - run: .github/build-pcsc-relay.sh ubuntu
    - uses: actions/upload-artifact@v4
      with:
        name: pcsc-relay
        path:
          pcsc-relay/pcsc-relay*.tar.gz

#  pcsc-relay-mingw-32:
#    runs-on: ubuntu-24.04
#    steps:
#    - uses: actions/checkout@v6
#    - run: .github/build-pcsc-relay.sh mingw-32

  pcsc-relay-mingw-64:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - run: .github/build-pcsc-relay.sh mingw-64
    - uses: actions/upload-artifact@v4
      with:
        name: pcsc-relay-mingw-64
        path:
          pcsc-relay/src/pcsc-relay.exe

  remote-reader-ubuntu:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - run: .github/build-remote-reader.sh
    - uses: actions/upload-artifact@v4
      with:
        name: remote-reader
        path:
          remote-reader/app/build/outputs/apk

  ACardEmulator-ubuntu:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - run: .github/build-ACardEmulator.sh
    - uses: actions/upload-artifact@v4
      with:
        name: ACardEmulator
        path:
          ACardEmulator/app/build/outputs/apk

  virtualsmartcard-windows:
    strategy:
      matrix:
        include:
          - os: windows-2025
            platform: x64
            vcvars: amd64
          - os: windows-2025
            platform: ARM64
            vcvars: arm64
    runs-on: ${{ matrix.os }}
    env:
      MSBUILD_PLATFORM: ${{ matrix.platform }}
      VCVARS_PLATFORM: ${{ matrix.vcvars }}
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - run: choco install windowsdriverkit10 -y
    - run: .github/build-virtualsmartcard.ps1
    - run: Move-Item -Path "virtualsmartcard\win32\BixVReaderInstaller\bin\x64\Release\BixVReaderInstaller.msi" -Destination "."
    - run: Move-Item -Path "virtualsmartcard\win32\install_vpcd.bat" -Destination "."
    - run: Move-Item -Path "virtualsmartcard\win32\uninstall_vpcd.bat" -Destination "."
    - run: Move-Item -Path "dist\vicc.exe" -Destination "."
    - run: Start-Process "install_vpcd.bat" -NoNewWindow -Wait
      # the runner is a x64 platform
      if: matrix.platform == 'x64'
    - run: Get-Content "install.log"
      # the runner is a x64 platform
      if: matrix.platform == 'x64'
    - uses: actions/upload-artifact@v4
      with:
        name: virtualsmartcard-win-${{ matrix.platform }}
        path: |
          install_vpcd.bat
          uninstall_vpcd.bat
          vicc.exe
          vpcd-config.exe
          BixVReaderInstaller.msi
          BixVReader.cer
